---
fixtures:
  symlinks:
    cron: "#{source_dir}"
  repositories:
    # Module requirements
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    # Acceptance testing requirements
    facts: https://github.com/puppetlabs/puppetlabs-facts
    provision: https://github.com/puppetlabs/provision
    puppet_agent: https://github.com/puppetlabs/puppetlabs-puppet_agent
...
