---
AllCops:
  Exclude:
    - spec/fixtures/**/*
    - spec/_fixtures/**/*
  TargetRubyVersion: 2.4
  DisplayCopNames: true

# Style
Style/NumericLiterals:
  Description: Counter-intuitive for port numbers.
  Enabled: false
Style/TrailingCommaInArguments:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/SpecialGlobalVars:
  Description: These look kinda scary.
  Enabled: false
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets

# Layout
Layout/ClosingParenthesisIndentation:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Max: 300
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 140
...
