---
AllCops:
  Exclude:
    - spec/spec_helper_acceptance.rb # FIXME
    - spec/fixtures/**/*
    - spec/_fixtures/**/*
    - vendor/**/*
    - pkg/**/*
    - bin/**/*
  TargetRubyVersion: 2.4
  DisplayCopNames: true

# Style
Style/ConditionalAssignment:
  Description: This looks way more readable.
  EnforcedStyle: assign_inside_condition
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MixinUsage:
  Description: spec_helper in PDK template is not behaving well.
  Exclude: [ spec/spec_helper.rb ]
Style/IfUnlessModifier:
  Description: spec_helper in PDK template is not behaving well.
  Exclude: [ spec/spec_helper.rb ]
Style/RescueStandardError:
  Description: spec_helper in PDK template is not behaving well.
  Exclude: [ spec/spec_helper.rb ]
Style/NumericLiterals:
  Description: Counter-intuitive for port numbers.
  Enabled: false
Style/TrailingCommaInArguments:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  Description: We like it Puppet-way.
  EnforcedStyleForMultiline: comma
Style/SpecialGlobalVars:
  Description: These look kinda scary.
  Enabled: false
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets
Style/WordArray:
  Description: Be consistent with Puppet arrays.
  EnforcedStyle: brackets
Style/FormatStringToken:
  Description: Hiera doesn't like this restriction.
  Enabled: false

# Layout
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

# Metrics
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 200
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
...
