---
spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - '  c.after(:suite) { RSpec::Puppet::Coverage.report!(100) }'
    - 'end'

appveyor.yml:
  delete: true

.rubocop.yml:
  unmanaged: true
.travis.yml:
  unmanaged: true
Gemfile:
  unmanaged: true
Rakefile:
  unmanaged: true
...
