---
language: ruby
install:
- bundle install --without acceptance
- bundle exec librarian-puppet install
script:
- bundle exec rake validate
- bundle exec rake spec
env:
- PUPPET_VERSION='4.4.1'
- PUPPET_VERSION='~> 4.0'
