---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: bundle exec rake $RAKE

jobs:
  include:
    - stage: unit
      env:
      - RAKE=test
      - PUPPET=4.10.4
    - env:
      - RAKE=test
      - PUPPET=4.10.6
    - env:
      - RAKE=test
      - PUPPET=5.1.0
    - stage: acceptance
      env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.6
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.4
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=5.1.0
      - PUPPET_INSTALL_TYPE=gem
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.6
      - BEAKER_set=ubuntu_1604
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.4
      - BEAKER_set=ubuntu_1604
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=5.1.0
      - BEAKER_set=ubuntu_1604
      - PUPPET_INSTALL_TYPE=gem
