---
language: ruby
rvm:
- 2.3.1
install:
- bundle install
- bundle exec librarian-puppet install
script:
- bundle exec rake validate
- bundle exec rake spec
- bundle exec rake beaker
dist: trusty
sudo: required
services: docker
matrix:
  fast_finish: true
  include:
  - env: PUPPET_VERSION=4.4.1 BEAKER_set=ubuntu_1404
  - env: PUPPET_VERSION=4.4.1 BEAKER_set=ubuntu_1604
  - env: PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu_1404
  - env: PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu_1604
