---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true

language: ruby

jobs:
  include:
    - stage: validate
      script: bundle exec rake validate_all
      env:
      - PUPPET='~> 4'
    - env:
      - PUPPET='~> 5'
    - stage: unit
      script: bundle exec rake spec
      env:
      - PUPPET='~> 4'
    - env:
      - PUPPET='~> 5'
    - stage: acceptance
      script: bundle exec rake beaker
      env:
      - PUPPET='~> 4'
      - BEAKER_set=ubuntu_1404
    - env:
      - PUPPET='~> 5'
      - BEAKER_set=ubuntu_1404
    - env:
      - PUPPET='~> 4'
      - BEAKER_set=ubuntu_1604
    - env:
      - PUPPET='~> 5'
      - BEAKER_set=ubuntu_1604
    - env:
      - PUPPET='~> 4'
      - BEAKER_set=ubuntu_1804
    - env:
      - PUPPET='~> 5'
      - BEAKER_set=ubuntu_1804
