---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: bundle exec rake $RAKE

jobs:
  include:
    - stage: validate
      env:
      - RAKE=validate_all
      - PUPPET='~> 4'
    - env:
      - RAKE=validate_all
      - PUPPET='~> 5'
    - stage: unit
      env:
      - RAKE=spec
      - PUPPET=4.10.9
    - env:
      - RAKE=spec
      - PUPPET='~> 4'
    - env:
      - RAKE=spec
      - PUPPET='~> 5'
    - stage: acceptance
      env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.9
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=5.4.0
      - PUPPET_INSTALL_TYPE=gem
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=1.10.9
      - BEAKER_set=ubuntu_1604
    - env:
      - RAKE=beaker
      - PUPPET_VERSION=5.4.0
      - BEAKER_set=ubuntu_1604
      - PUPPET_INSTALL_TYPE=gem
