---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: travis_retry bundle exec rake $T

jobs:
  include:
    - stage: unit
      env:
      - T=test
      - PUPPET=4.10.4
    - env:
      - T=test
      - PUPPET=4.10.6
    - env:
      - T=test
      - PUPPET=5.1.0
    - stage: acceptance
      env:
      - T=beaker
      - PUPPET_VERSION=4.10.6
      - BEAKER_debug=true
    - env:
      - T=beaker
      - PUPPET_VERSION=5.1.0
      - BEAKER_debug=true
      - PUPPET_INSTALL_TYPE=gem
