---
language: ruby
install:
- bundle install
- bundle exec librarian-puppet install
script: bundle exec rake validate spec beaker
rvm: 2.3.1
dist: trusty
sudo: required
services: docker
fast_finish: true
env:
- PUPPET=4.4.1 PUPPET_AGENT=1.4.1 BEAKER_set=ubuntu_1404
- PUPPET=4.4.1 PUPPET_AGENT=1.4.2 BEAKER_set=ubuntu_1604
- PUPPET=4.8.2 PUPPET_AGENT=1.8.3 BEAKER_set=ubuntu_1404
- PUPPET=4.8.2 PUPPET_AGENT=1.8.3 BEAKER_set=ubuntu_1604
