---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true
cache: bundler

language: ruby

script: bundle exec rake $DO

jobs:
  include:
    - stage: validate
      env:
      - DO=validate_all
      - PUPPET='~> 4'
    - env:
      - DO=validate_all
      - PUPPET='~> 5'
    - env:
        - DO=validate_all
        - PUPPET='~> 6'
    - stage: unit
      env:
      - DO=spec
      - PUPPET='~> 4'
    - env:
      - DO=spec
      - PUPPET='~> 5'
    - env:
        - DO=spec
        - PUPPET='~> 6'
    - stage: acceptance
      env:
      - DO=beaker
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_set=ubuntu_1404
    - env:
      - DO=beaker
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_set=ubuntu_1604
    - env:
      - DO=beaker
      - BEAKER_PUPPET_COLLECTION=puppet6
      - BEAKER_set=ubuntu_1604
    - env:
      - DO=beaker
      - BEAKER_PUPPET_COLLECTION=puppet5
      - BEAKER_set=ubuntu_1804
    - env:
      - DO=beaker
      - BEAKER_PUPPET_COLLECTION=puppet6
      - BEAKER_set=ubuntu_1804
    - stage: deploy
      script: true
      env:
      - DEPLOY_TO_FORGE=yes

deploy:
  provider: puppetforge
  user: pegas
  password:
    secure: "OxeJtBFZZfQkJJBLVjoN4J2ibifeFPnT01ntpT2ulgReKt8Z7+5DMZWNibids/miQPbYfmei82G/0XQzd1T0HQTvQiRqcqbC61k72qWanW2kwRTwOQhuRiIKj0TvMh/Rc61Fnp5nMT+bYpap25Y+9Jt5GE5z/Rj0SsgXmA0EaMRfyrNQyJ5SSgZQ5e4TXR/ZfvtIG0xOrG9eI2lDly0xXIw0InEgbHvW/+vIQFPizZoq3zr3rknGzhwp7l0s6XA3+tVHWOJo+FZRMPa7XV+b2JbFYRJlGkESyNo4hh4l6onsJoKhuVwHEPWn/ozTLFYNduOhA+avIJE5MCxZwq3bdIxcvkOYxQYZh8MvWBuPtgRaOXer29lTFsYJpbr5Gatp6wRB+m9s/Pnh+bME3tLqxk3oOUx8pVilHMwzVFCXGEwsiYiDmSXeyVddLKwo0nRT3ifMfwiFzdPE6k6L4Hp1D7G2VowJ0KfDIRWjzwMi3++fnkLN4LHwVp0zEnrAoHPZUDNPWqlaFNx/s9Omu1tlee10L2vn1HK948OPVe1TfHanay1adKWDPXFNYt4WTpz/UMnHczcIXqwUf9JddXVPmNDTL6mDFoLAfiBzwzcRHWdyEEfxOQpUpM7zqHY1W75b/D8/fZGXKCRORz7Sowg9bR4tPsq6UlV3BzQJIetNJFk="
  on:
    tags: true
    all_branches: false
    condition: "$DEPLOY_TO_FORGE = yes"
