---
sudo: false
services:
- docker

before_install: rm Gemfile.lock || true
bundler_args: --without acceptance
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: travis_retry bundle exec rake $RAKE_TASK

jobs:
  include:
    - stage: unit
      env:
      - RAKE_TASK=test
      - PUPPET=4.4.1
    - env:
      - RAKE_TASK=test
      - PUPPET=4.10.4
    - env:
      - RAKE_TASK=test
      - PUPPET=4.10.6
    - env:
      - RAKE_TASK=test
      - PUPPET=5.1.0
    - stage: acceptance
      env:
      - RAKE_TASK=beaker
      - BEAKER_debug=true
      - PUPPET_INSTALL_VERSION=4.10.6
    - env:
      - RAKE_TASK=beaker
      - BEAKER_debug=true
      - PUPPET_INSTALL_TYPE=gem
      - PUPPET_VERSION=5.1.0
