---
language: ruby
install:
- bundle install
script: bundle exec rake test
rvm: 2.4.1
dist: trusty
sudo: required
services: docker
fast_finish: true
env:
- PUPPET=4.10.6 PUPPET_AGENT=1.10.6 BEAKER_set=ubuntu_1404
- PUPPET=4.10.6 PUPPET_AGENT=1.10.6 BEAKER_set=ubuntu_1604
- PUPPET=5.0.1 PUPPET_AGENT=5.0.1 BEAKER_set=ubuntu_1404
- PUPPET=5.0.1 PUPPET_AGENT=5.0.1 BEAKER_set=ubuntu_1604
