---
sudo: false
services:
- docker

bundler_args: --without acceptance
language: ruby
script: bundle exec rake $RAKE_TASK

jobs:
  include:
    - env:
      - TASK=test
      - PUPPET=4.4.1
    - env:
      - TASK=test
      - PUPPET=4.10.4
    - env:
      - TASK=test
      - PUPPET=4.10.6
    - env:
      - TASK=test
      - PUPPET=5.1.0
    - env:
      - TASK=beaker
      - BEAKER_debug=true
      - PUPPET_INSTALL_VERSION=4.10.6
    - env:
      - TASK=beaker
      - BEAKER_debug=true
      - PUPPET_INSTALL_TYPE=gem
      - PUPPET_VERSION=5.1.0
