---
sudo: false
services:
- docker

before_install: rm Gemfile.lock || true
bundler_args: --without acceptance
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: travis_retry bundle exec rake $TASK

jobs:
  include:
    - stage: unit
      env:
      - TASK=test
      - PUPPET=4.4.1
    - env:
      - TASK=test
      - PUPPET=4.10.4
    - env:
      - TASK=test
      - PUPPET=4.10.6
    - env:
      - TASK=test
      - PUPPET=5.1.0
    - stage: acceptance
      env:
      - TASK=beaker
      - PUPPET_VERSION=4.10.6
      - BEAKER_debug=true
      sudo: required
    - env:
      - TASK=beaker
      - PUPPET_VERSION=5.1.0
      - BEAKER_debug=true
      - PUPPET_INSTALL_TYPE=gem
      sudo: required
