---
language: ruby
rmv:
- 2.3.1
install:
- bundle install
- bundle exec librarian-puppet install
script:
- bundle exec rake validate
- bundle exec rake spec
- bundle exec rake beaker
dist: trusty
services: docker
sudo: required
matrix:
  fast_finish: true
  include:
  - env: PUPPET_VERSION=4.4.1 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=default
  - env: PUPPET_VERSION=4.4.1 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu_1604
  - env: PUPPET_VERSION=4.8.2 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=default
  - env: PUPPET_VERSION=4.8.2 PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu_1604
