---
name: Release

on:
  push:
    tags: [ '*' ]

jobs:
  docs:
    name: GitHub Pages
    runs-on: ubuntu-latest
    env:
      PUPPET_GEM_VERSION: "~> 8.0"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          echo 'machine github.com' > ~/.netrc
          echo "login ${{ github.actor }}" >> ~/.netrc
          echo "password ${{ github.token }}" >> ~/.netrc

      - name: Publish
        run: bundle exec rake strings:gh_pages:update

  release:
    name: 'Puppet Forge'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build module
        uses: docker://puppet/pdk:nightly
        with:
          args: build

      - name: Publish module
        uses: docker://puppet/pdk:nightly
        with:
          args: release publish --forge-token ${{ secrets.PUPPET_FORGE_API_KEY }}
...
